# Generated by Django 3.0 on 2020-10-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20201009_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='specialist_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(blank=True, help_text='Choose the doctor', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Specialist'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='hospital',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
