# Generated by Django 3.0 on 2020-10-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20201012_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
    ]
