# Generated by Django 3.0 on 2020-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_user_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doc_image/'),
        ),
    ]
