# Generated by Django 3.0 on 2020-11-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_specialist_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_name',
            new_name='name',
        ),
    ]
