# Generated by Django 3.0 on 2020-11-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20201101_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user_id',
            new_name='user',
        ),
    ]
